"""Add document status enum and fields

Revision ID: 8c4e950ed35c
Revises: d2bf66afed31
Create Date: 2024-11-09 11:54:59.265408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c4e950ed35c'
down_revision: Union[str, None] = 'd2bf66afed31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('identity_documents', sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', 'EXPIRED', 'REVOKED', name='documentstatus'), nullable=True))
    op.add_column('verified_documents', sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', 'EXPIRED', 'REVOKED', name='documentstatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verified_documents', 'status')
    op.drop_column('identity_documents', 'status')
    # ### end Alembic commands ###
